services:
    prestashop.module.FormGenerator.repository.form_repository:
        class: Module\FormGenerator\Repository\FormRepository
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Module\FormGenerator\Entity\Form

    prestashop.module.FormGenerator.forms.install:
        class: Module\FormGenerator\Database\FormInstaller
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
