# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_FormGenerator_form_index:
    path: /demo-doctrine/forms
    methods: [GET]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::indexAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm'

ps_FormGenerator_form_search:
    path: /demo-doctrine/forms
    methods: [POST]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::searchAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:search'

ps_FormGenerator_form_generate:
    path: /demo-doctrine/generate
    methods: [GET, POST]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::generateAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:generate'

ps_FormGenerator_form_create:
    path: /demo-doctrine/forms/new
    methods: [GET, POST]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::createAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:add'

ps_FormGenerator_form_edit:
    path: /demo-doctrine/forms/{formId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::editAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:edit'
    requirements:
        formId: \d+

ps_FormGenerator_form_delete:
    path: /demo-doctrine/forms/{formId}/delete
    methods: [DELETE]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::deleteAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:deleteform'
    requirements:
        formId: \d+

ps_FormGenerator_form_bulk_delete:
    path: /demo-doctrine/forms/bulkDelete
    methods: [POST]
    defaults:
        _controller: 'Module\FormGenerator\Controller\Admin\FormsController::deleteBulkAction'
        _legacy_controller: 'AdminFormGeneratorForm'
        _legacy_link: 'AdminFormGeneratorForm:submitBulkdeleteform'
